EXTRA_POST_BUILD_TARGETS += $(MXOS_ALL_BIN_OUTPUT_FILE)

#bootloader
BOOT_BIN_FILE := $(MXOS_OS_PATH)/platform/MCU/mx1270/image/boot.bin
BOOT_OFFSET   := 0x0

#application 
APP_BIN_FILE := $(BIN_OUTPUT_FILE)
APP_OFFSET := 0xA000

#ate firmware
ATE_BIN_FILE := $(MXOS_OS_PATH)/platform/MCU/mx1270/image/ate.bin
ATE_OFFSET := 0x100000

# Required to build Full binary file
GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT:= $(SCRIPTS_PATH)/gen_common_bin_output_file.py

MXOS_ALL_BIN_OUTPUT_FILE :=$(LINK_OUTPUT_FILE:$(LINK_OUTPUT_SUFFIX)=.all$(BIN_OUTPUT_SUFFIX))

$(MXOS_ALL_BIN_OUTPUT_FILE): $(OTA_BIN_OUTPUT_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f $(BOOT_OFFSET) $(BOOT_BIN_FILE)              
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f $(APP_OFFSET)  $(APP_BIN_FILE)
	$(PYTHON) $(GEN_COMMON_BIN_OUTPUT_FILE_SCRIPT) -o $(MXOS_ALL_BIN_OUTPUT_FILE) -f $(ATE_OFFSET)  $(ATE_BIN_FILE)